apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://github.com/ZuyzuyAnh/platform-configuration.git"
    targetRevision: master
    path: clusters/management/metallb
    plugin:
      name: kustomize-helm
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
