apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/metallb

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: "0.14.3"
    releaseName: metallb
    namespace: metallb-system
    valuesFile: values.yaml
