# Controller manages the MetalLB deployment
controller:
  image:
    repository: quay.io/metallb/controller
  # High availability setup for production can be enabled later
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - controller
            topologyKey: kubernetes.io/hostname

# Speaker settings
speaker:
  image:
    repository: quay.io/metallb/speaker
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  # Speaker must run on all nodes to announce IPs
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

# IP Address Pool Configuration
ipAddressPools:
  - name: default
    addresses:
      # Will be replaced with actual IP range on real environment
      - 192.168.1.240-192.168.1.250
    autoAssign: true
    avoidBuggyIPs: true

l2Advertisements:
  - name: default-l2
    ipAddressPools:
      - default
    # Optional: Specify specific interfaces to announce on
    # interfaces:
    # - eth0

# # Enable prometheus metrics
# prometheus:
#   podMonitor:
#     enabled: false
#   serviceMonitor:
#     enabled: false

# Logging configuration
logging:
  level: info
