apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: "1.10.2"
    releaseName: harbor
    namespace: harbor-system
